name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
  push:
  pull_request:

env:
  MAVEN_SETTING: '/home/ec2-user/maven/.m2/settings.xml'
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: self-hosted
    if: github.repository_owner == 'ikmdev'
    steps:
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}